Pull makeImage into its own package (from screenshoter) (#1061)
* js/image: pull image into its own project

* js/image: convert package to ts (and add missing libs/dot-files for eslint, yarn, etc)

* js/image: first pass on types, fixes build errors

* js/image: set skipLibCheck: true

To overcome the following error from png-async's type definitions:

```
node_modules/png-async/lib/index.d.ts:40:5 - error TS2416: Property 'end' in type 'Image' is not assignable to the same property in base type 'Duplex'.
  Type '(data?: any) => void' is not assignable to type '{ (cb?: () => void): this; (chunk: any, cb?: () => void): this; (chunk: any, encoding?: string, cb?: () => void): this; }'.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

40     end(data?: any): void;
       ~~~
```

* js/image: fix test deps/imports & type errors

* js/image: declare image type

* NO_CHANGELOG

* js/image: improved Image types to be more specific

* js/screenshoter: update it to use makeImage from @applitools/image (still need to publish the package and update the package.json accordingly)

* js/image: add missing dep (bongo)

* js/image: add fixed dep versions

* js/image: update package based on feedback

- create separate image.ts file and export it from index
- rename index.spec.ts to image.spec.ts
- use a named export
- use an interface instead of a type for `Image`

* js/image: fix lint

* js/screenshoter: update dep from local to public version on npm

* js/screenshoter: update requires for makeImage to use the named import

* Update js/packages/image/src/image.ts

Co-authored-by: Kyrylo <59825365+kyryloonufriiev@users.noreply.github.com>

* js/image: add test:sanity

* gh action: add publish action for js/image

* Update js/packages/image/package.json

Co-authored-by: Kyrylo <59825365+kyryloonufriiev@users.noreply.github.com>

* js/image: add @applitools/scripts as dev dep

Co-authored-by: Kyrylo <59825365+kyryloonufriiev@users.noreply.github.com>